'use strict';

const STORAGE_KEY = 'sigilrpg-stat-tracker-v1';
const UI_KEY = 'sigilrpg-ui-v2';
const LOCALE_KEY = 'sigilrpg-locale-v1';
const ATTRIBUTES = ['STR','DEX','CON','INT','SEN','AUR'];
const DICE = [4,6,8,10,12,20,100];
const LOCALES = window.SIGILRPG_LOCALES || {en:{label:'English',htmlLang:'en',strings:{}}};
const PREFIXES = {
  precision:{label:'Precision',word:'Zin',potential:1,effects:['Gain advantage on the accuracy roll.','One attribute may be wounded twice by this attack.']},
  power:{label:'Power',word:'Tor',potential:1,effects:['Accuracy die increases by one tier.']},
  dashing:{label:'Dashing',word:'Vesh',potential:1,effects:[]},
  disarming:{label:'Disarming',word:'Nek',potential:1,effects:['On a failed enemy Brace, the enemy drops a held item. The normal damage chain is unchanged.']},
  knockback:{label:'Knockback',word:'Brom',potential:1,effects:[]},
  sweep:{label:'Sweep',word:'Sha',potential:0,effects:['Apply the attack against multiple targets.','Sweep does not increase damage potential.']}
};
const TEMPLATES = [
  {id:'blank',name:'Blank',stats:[4,4,4,4,4,4]},
  {id:'hero',name:'Hero',stats:[8,8,8,8,8,8]},
  {id:'guard',name:'Guard',stats:[8,6,8,4,6,4]},
  {id:'brute',name:'Brute',stats:[12,6,10,4,6,4]},
  {id:'mystic',name:'Mystic',stats:[4,6,6,12,10,8]}
];
const DEFAULT_WEAPONS = [
  {name:'Long Blade',weaponClass:'heavy',accuracy:'STR',impact:8,equipped:true},
  {name:'Dagger',weaponClass:'light',accuracy:'DEX',impact:4,equipped:true}
];
const BASE_ATTACK_POTENTIAL = 2;
const WEAPON_CLASSES = {
  light:{label:'Light',accuracyOptions:['STR','DEX']},
  ranged:{label:'Ranged',accuracyOptions:['STR','DEX']},
  heavy:{label:'Heavy',accuracyOptions:ATTRIBUTES}
};
const PLATING_TYPES = {
  light:{label:'Light',braceGuarantee:6,dodgeLimit:12},
  medium:{label:'Medium',braceGuarantee:9,dodgeLimit:9},
  heavy:{label:'Heavy',braceGuarantee:12,dodgeLimit:6}
};

const WORDS = {
  source:[
    {id:'thunder',name:'Thunder & Lightning',word:'Baguaga',mana:1,delivery:'payload',target:'creatures and conductive objects',area:'follows delivery',range:'follows delivery',duration:'instant',resist:'follows delivery',effects:{touch:'Shock a touched target.',smite:'Add lightning to the hit and zap one nearby target with a chip attack.',attack:'Electrify the struck target; arc a chip zap to one nearby target.',area:'Each affected target is shocked; one nearby target at the area edge takes a chip zap.'},interactions:'Water and metal may conduct the visible arc when the table agrees.',potentialPolicy:'resource'},
    {id:'vital',name:'Vital Energy',word:'Habaga',mana:1,delivery:'payload',target:'living creature or undead',area:'follows delivery',range:'follows delivery',duration:'instant',resist:'willing targets need none; harmful inversion follows delivery',effects:{touch:'Restore living tissue by touch, or invert it to harm.',smite:'Vital Smite is restorative or -1 damage potential; against undead it is +2 damage potential.',attack:'Deliver restoration or inverted vitality through the hit.',area:'Restore living creatures or harm them with inverted vitality throughout the area.'},interactions:'With Slash, Strike, or another cutting Shape, Vital can become surgical: remove dead tissue before regeneration.',potentialPolicy:'resource'},
    {id:'force',name:'Force',word:'Tyś',mana:1,delivery:'payload',target:'creature or object',area:'follows delivery',range:'follows delivery',duration:'instant',resist:'follows delivery',effects:{touch:'Apply a sharp shove or controlled pressure by touch.',smite:'Add physical impact and momentum to the hit.',attack:'Strike with impact, pressure, or acceleration.',area:'Push or buffet occupants in the resolved area.'},interactions:'Hammer emphasizes impact; Barrier makes pressure resist movement.',potentialPolicy:'resource'},
    {id:'fire',name:'Fire',word:'Firanka',mana:1,delivery:'payload',target:'creature, object, or space',area:'follows delivery',range:'follows delivery',duration:'ignite: 2 rounds',resist:'follows delivery',effects:{touch:'Sear or kindle what is touched.',smite:'Ignite the struck target; it takes a chip attack at the end of each of its next 2 turns.',attack:'Ignite the hit target; chip attack at the end of each of its next 2 turns.',area:'Ignite affected creatures and flammables; chip attack at the end of each affected creature’s next 2 turns.'},interactions:'Vortex spreads flame through its field; Pillar forms a vertical column of flame.',potentialPolicy:'resource'},
    {id:'frost',name:'Frost',word:'Zhorna',mana:1,delivery:'payload',target:'creature, object, or water',area:'follows delivery',range:'follows delivery',duration:'slowed for 1 round',resist:'follows delivery',effects:{touch:'Rime the target and halve its speed for 1 round.',smite:'The struck target’s speed is halved for 1 round.',attack:'The hit target’s speed is halved for 1 round.',area:'Affected creatures have half speed for 1 round.'},interactions:'Water freezes into slippery or solid forms; Barrier can become an ice wall.',potentialPolicy:'resource'},
    {id:'echoes',name:'Echoes',word:'Berevri',mana:1,delivery:'payload',target:'a lingering spell trace',area:'matches the echoed trace',range:'20 m',duration:'one repetition, no longer than original',resist:'as the echoed spell',effects:{touch:'Replay a faint remnant at the touched trace.',smite:'Overlay the hit with a faint echo of a previous spell.',attack:'Carry a compatible lingering spell remnant to the hit.',area:'Repeat a compatible remnant through the resolved area.'},interactions:'Requires an identifiable earlier spell; if none exists, report an unresolved requirement.',potentialPolicy:'resource'},
    {id:'shadow',name:'Shadow & Darkness',word:'Ferpshna',mana:1,delivery:'payload',target:'creature, object, or space',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'follows delivery',effects:{touch:'Cloak the touched subject in dim shadow.',smite:'The hit blooms with obscuring darkness for 1 round.',attack:'Obscure the hit target’s immediate space for 1 round.',area:'Heavily obscure the resolved area for 1 round.'},interactions:'Light contests or outlines the darkness instead of silently cancelling it.',potentialPolicy:'resource'},
    {id:'light',name:'Light & Radiance',word:'Gripshna',mana:1,delivery:'payload',target:'creature, object, or space',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'follows delivery',effects:{touch:'Illuminate or brand the touched subject.',smite:'The hit flashes; the target is visibly outlined for 1 round.',attack:'Radiance outlines the hit target for 1 round.',area:'Brightly illuminate and outline occupants in the resolved area for 1 round.'},interactions:'Shadow creates a visible boundary or contested illumination.',potentialPolicy:'resource'},
    {id:'poison',name:'Poison',word:'Vyrnaka',mana:1,delivery:'payload',target:'living creature or contaminable object',area:'follows delivery',range:'follows delivery',duration:'2 rounds',resist:'follows delivery',effects:{touch:'Apply venom by touch; chip attack at the end of the target’s next 2 turns.',smite:'Poison the struck target; chip attack at the end of its next 2 turns.',attack:'Poison the hit target for 2 rounds.',area:'Expose living occupants; affected targets suffer poison for 2 rounds.'},interactions:'Water can carry and dilute poison; Siphon can draw it out.',potentialPolicy:'resource'},
    {id:'fear',name:'Fear',word:'Ghazur',mana:1,delivery:'payload',target:'creature able to perceive the manifestation',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'target resistance',effects:{touch:'Fill the touched creature with dread for 1 round.',smite:'The hit target recoils in supernatural fear for 1 round.',attack:'The hit target is frightened for 1 round.',area:'Affected perceiving creatures are frightened for 1 round.'},interactions:'Power Word can deliver fear through hearing.',potentialPolicy:'resource'},
    {id:'water',name:'Water',word:'Tugatuga',mana:1,delivery:'payload',target:'creature, object, or space',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'follows delivery',effects:{touch:'Drench or move a handful of water by touch.',smite:'The hit bursts with water and leaves the target drenched.',attack:'Strike and drench the hit target.',area:'Fill or drench the resolved area for 1 round.'},interactions:'Lightning may conduct through it; Frost may freeze it; Vortex makes a whirlpool.',potentialPolicy:'resource'},
    {id:'speed',name:'Speed',word:'Dobenga',mana:1,delivery:'payload',target:'creature or moving object',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'willing targets need none; harmful acceleration follows delivery',effects:{touch:'Double the touched target’s movement speed for 1 round.',smite:'Accelerate the wielder through the strike; reposition 5 m after it.',attack:'Accelerate the hit or launched payload.',area:'Double affected willing creatures’ speed for 1 round.'},interactions:'Wings converts acceleration into fast flight; Spiral curves the motion.',potentialPolicy:'resource'},
    {id:'levitate',name:'Levitation',word:'Harnharn',mana:1,delivery:'payload',target:'creature or object',area:'follows delivery',range:'follows delivery',duration:'1 round',resist:'unwilling targets resist',effects:{touch:'Lift the touched target just above the ground for 1 round.',smite:'Briefly lift the struck target or wielder.',attack:'Lift the hit target for 1 round.',area:'Lift affected creatures and loose objects for 1 round.'},interactions:'Wings grants controlled flight; Pillar lifts along a vertical path.',potentialPolicy:'resource'},
    {id:'stone',name:'Stone',word:'Kafelka',mana:1,delivery:'payload',target:'earth, stone, creature, object, or space',area:'follows delivery',range:'follows delivery',duration:'1 minute',resist:'follows delivery',effects:{touch:'Harden or shape touched earth and stone.',smite:'Sheathe the hit in stone and scatter chips.',attack:'Strike with stone or petrifying crust.',area:'Raise or reshape stone throughout the resolved area.'},interactions:'Pillar raises a stone column; Cave excavates it; Shatter breaks it apart.',potentialPolicy:'resource'}
  ],
  shape:[
    {id:'pillar',name:'Pillar',word:'Ghyblor',mana:1,delivery:'container',target:'occupants of its footprint',area:'1 m-wide × 5 m-tall pillar',range:'20 m or delivery impact',duration:'1 round',resist:'area resistance',effects:['Manifest the Source as a narrow vertical pillar.'],interactions:'A primary delivery carries and places the Pillar at its endpoint; Bolt + Pillar attacks one target, then manifests the Pillar at the impact point and affects occupants in its footprint.',potentialPolicy:'resource'},
    {id:'bolt',name:'Bolt',word:'Dziahaka',mana:1,attackLike:true,delivery:'primary-attack',target:'one target',area:'impact point',range:'30 m',duration:'instant; containers may persist',resist:'spell accuracy vs target defense',effects:['Launch the payload at one target.'],interactions:'Carries area/container Shapes to the target or impact point.',potentialPolicy:'resource'},
    {id:'vortex',name:'Vortex',word:'Kashanka',mana:1,delivery:'container',target:'occupants',area:'5 m-radius field',range:'20 m or delivery impact',duration:'1 round',resist:'area resistance',effects:['Rotate, pull, or circulate the payload in a field.'],interactions:'A primary delivery places the Vortex at its endpoint; without one, choose its center in range.',potentialPolicy:'resource'},
    {id:'hammer',name:'Hammer',word:'Baluuga',mana:1,attackLike:true,delivery:'primary-attack',target:'one target',area:'impact point',range:'10 m',duration:'instant',resist:'spell accuracy vs target defense',effects:['Deliver a heavy impact that may push or stagger.'],interactions:'Carries containers to the impact point and emphasizes Force or Stone impact.',potentialPolicy:'resource'},
    {id:'strike',name:'Strike',word:'Hypsh',mana:1,attackLike:true,delivery:'primary-attack',target:'one touched or melee target',area:'contact point',range:'touch/melee',duration:'instant',resist:'spell accuracy vs target defense',effects:['Deliver the payload by touch or melee strike.'],interactions:'With Vital or a cutting Shape, permits surgical removal of dead tissue.',potentialPolicy:'resource'},
    {id:'slash',name:'Slash',word:'Yyś',mana:1,attackLike:true,delivery:'primary-attack',target:'one target along the line',area:'10 m × 1 m line',range:'10 m',duration:'instant',resist:'spell accuracy for primary target; area resistance for other occupants',effects:['Cut a narrow line through the payload.'],interactions:'With Vital, becomes a surgical cutting manifestation; containers originate at the chosen impact.',potentialPolicy:'resource'},
    {id:'snake',name:'Snake',word:'Sneila',mana:1,attackLike:true,delivery:'primary-attack',target:'one target around simple cover',area:'winding path',range:'30 m',duration:'instant',resist:'spell accuracy vs target defense',effects:['Guide the payload around simple cover.'],interactions:'Spiral further curves its path; containers manifest at the endpoint.',potentialPolicy:'resource'},
    {id:'knockdown',name:'Knockdown / Pindown',word:'Kuva',mana:1,delivery:'modifier',target:'target or occupants',area:'follows delivery',range:'follows delivery',duration:'1 round while pinned',resist:'target resistance',effects:['Knock affected targets prone; continued pressure may pin them.'],interactions:'Uses the primary target when carried, otherwise requires a target in 20 m.',potentialPolicy:'resource'},
    {id:'chains',name:'Chains / Restrain',word:'Thryka',mana:1,delivery:'modifier',target:'target or occupants',area:'follows delivery',range:'20 m or follows delivery',duration:'1 round',resist:'target resistance',effects:['Restrain affected targets until they break free or the effect ends.'],interactions:'Container Shapes distribute chains among their occupants.',potentialPolicy:'resource'},
    {id:'barrier',name:'Barrier / Shield',word:'Oshvar',mana:1,delivery:'container',target:'creatures behind or crossing it',area:'3 m × 3 m plane',range:'20 m or delivery impact',duration:'1 round',resist:'none unless forced onto a target',effects:['Form a defensive plane from the payload.'],interactions:'Flat reinforces its plane; a primary delivery places it at the endpoint.',potentialPolicy:'resource'},
    {id:'siphon',name:'Siphon / Drain',word:'Drynok',mana:1,attackLike:true,delivery:'primary-attack',target:'one target',area:'line to caster',range:'10 m',duration:'instant',resist:'spell accuracy vs target defense',effects:['Draw the Source energy from the target toward the caster.'],interactions:'Vital drains life when inverted; Poison can be drawn out instead of inflicted.',potentialPolicy:'resource'},
    {id:'construct',name:'Construct / Frame',word:'Peyoz',mana:1,delivery:'container',target:'simple formed object',area:'within a 2 m cube',range:'20 m or delivery impact',duration:'1 minute',resist:'none unless trapping a target',effects:['Form a simple object or frame from the payload.'],interactions:'Other Shapes define the frame’s geometry or movement.',potentialPolicy:'resource'},
    {id:'heart',name:'Heart / Center',word:'Hordum',mana:1,delivery:'anchor',target:'spell center',area:'point anchor',range:'20 m or delivery impact',duration:'matches longest Shape',resist:'none',effects:['Give the spell a stable center.'],interactions:'Containers orbit or emanate from the Heart.',potentialPolicy:'resource'},
    {id:'illusion',name:'Illusion / Veil',word:'Lorynka',mana:1,delivery:'container',target:'observers or occupants',area:'5 m cube',range:'20 m or delivery impact',duration:'1 minute',resist:'target resistance when disbelief matters',effects:['Alter sight and sound in the resolved area.'],interactions:'Sources determine the illusion’s sensory theme; Power Word adds audible delivery.',potentialPolicy:'resource'},
    {id:'wings',name:'Wings / Flight',word:'Chyvra',mana:1,delivery:'modifier',target:'one creature or carried target',area:'target',range:'touch or follows delivery',duration:'1 round',resist:'unwilling target resists',effects:['Grant flight at base movement speed.'],interactions:'Speed increases flight speed; area delivery can grant flight to occupants.',potentialPolicy:'resource'},
    {id:'shatter',name:'Shatter',word:'Talgru',mana:1,attackLike:true,delivery:'primary-attack',target:'one creature, object, or construct',area:'target',range:'20 m',duration:'instant',resist:'spell accuracy vs target defense',effects:['Tear apart the target; especially apt against objects and constructs.'],interactions:'Stone supplies fragments; containers shatter at the endpoint.',potentialPolicy:'resource'},
    {id:'howling',name:'Howling',word:'Galish',mana:1,delivery:'area',target:'occupants',area:'10 m cone',range:'self-origin',duration:'instant',resist:'area resistance',effects:['Release the payload through a cone of sound or pressure.'],interactions:'Without a primary delivery the cone originates from the caster; Power Word carries it through hearing instead.',potentialPolicy:'resource'},
    {id:'open',name:'Open',word:'Alhora',mana:1,delivery:'modifier',target:'valid opening or closed object',area:'target',range:'10 m or follows delivery',duration:'instant',resist:'target resistance if held or warded',effects:['Open, unfold, or create an aperture.'],interactions:'Cave makes a passage; Barrier becomes a doorway or gap.',potentialPolicy:'resource'},
    {id:'spiral',name:'Spiral',word:'Panteka',mana:1,delivery:'modifier',target:'another Shape',area:'follows modified Shape',range:'follows modified Shape',duration:'follows modified Shape',resist:'follows delivery',effects:['Twist another Shape into a spiral or orbit.'],interactions:'Requires another Shape; modifies its path rather than becoming a delivery.',potentialPolicy:'resource'},
    {id:'cave',name:'Cave / Burrow',word:'Bûnkra',mana:1,delivery:'area',target:'earth or stone',area:'2 m-long × 2 m-wide passage',range:'touch/adjacent',duration:'persistent excavation',resist:'none',effects:['Excavate or shape a short passage.'],interactions:'Stone supplies material; Open creates an entrance.',potentialPolicy:'resource'},
    {id:'flat',name:'Flat',word:'Regal',mana:1,delivery:'modifier',target:'another Shape',area:'plane, wall, floor, or surface',range:'follows modified Shape',duration:'follows modified Shape',resist:'follows delivery',effects:['Flatten another Shape into a plane.'],interactions:'Requires another Shape; modifies its geometry rather than becoming a delivery.',potentialPolicy:'resource'}
  ],
  mastery:[
    {id:'negation',name:'Negation',word:'Nushik',mana:1,delivery:'mastery',target:'one selected Source or Shape',area:'follows affected Word',range:'follows delivery',duration:'follows affected Word',resist:'follows delivery',effects:['Invert, suppress, or cancel a selected Source or Shape where fiction permits.'],interactions:'The caster must state which Word is negated.',potentialPolicy:'resource'},
    {id:'power',name:'Power Word',word:'Dovinus',dust:1,delivery:'mastery-hearing',target:'anything that can hear',area:'audible reach',range:'hearing',duration:'follows payload',resist:'target resistance',effects:['Make the spell verbal-only, carry it through hearing, and raise its power die one tier.'],interactions:'Overrides ordinary delivery with hearing and distributes compatible Shapes to listeners.',potentialPolicy:'resource'},
    {id:'focus',name:'Focus Word',word:'Balrurg',dust:1,delivery:'mastery',target:'caster',area:'none',range:'self',duration:'casting',resist:'none',effects:['Gain advantage on the caster’s Spell Casting Check.'],interactions:'Does not alter target resistance.',potentialPolicy:'resource'},
    {id:'enhancement',name:'Enhancement',word:'Mabufa',mana:1,delivery:'mastery-touch',target:'one touched target',area:'target',range:'touch or compatible delivery',duration:'temporary over-max boost: until scene ends; healing is immediate',resist:'willing target: none',effects:['Transfer 1 Mana OR raise one target stat by one tier, healing a lost tier or granting a temporary over-maximum boost (for example d12 → d20). No character state is changed by this resolver.'],interactions:'Primarily utility; its spent Mana still adds 1 potential under the tracker resource ruling.',potentialPolicy:'resource'},
    {id:'ascended',name:'Ascended Energy',word:'Divinarius',dust:1,delivery:'mastery',target:'spell',area:'none',range:'self',duration:'casting',resist:'none',effects:['Raise the spell’s guaranteed success difficulty by one tier.'],interactions:'Does not alter target resistance.',potentialPolicy:'resource'},
    {id:'hold',name:'Hold Still',word:'Kurwa',delivery:'mastery',target:'caster',area:'none',range:'self',duration:'charging',resist:'none',effects:['Deliberately remain exposed while stabilizing and charging; reduce casting difficulty one tier when a casting check exists.'],interactions:'Never reduces target resistance and adds no potential because it consumes no energy.',potentialPolicy:'none'},
    {id:'show',name:'Show Me',word:'Gabbergûbber',dust:1,delivery:'mastery-vision',target:'caster',area:'vision',range:'self',duration:'brief vision',resist:'none',effects:['Reveal a simple vision; three uses can reveal a Vision of the World.'],interactions:'Other Words may narrow the subject of the vision.',potentialPolicy:'resource'},
    {id:'multiplier',name:'Multiplier',word:'Tigiba',dust:1,delivery:'mastery',target:'one compatible spell part',area:'follows multiplied part',range:'follows delivery',duration:'follows multiplied part',resist:'follows delivery',effects:['Repeat or multiply one compatible part of the spell.'],interactions:'Exact scaling remains a table decision; the resolver does not invent extra targets or potential.',potentialPolicy:'resource'}
  ]
};
const CASTING_DIFFICULTIES=[{name:'Easy',dc:4},{name:'Advanced',dc:6},{name:'Hard',dc:8},{name:'Very Hard',dc:10},{name:'Improbable',dc:12},{name:'Inconceivable',dc:20},{name:'Impossible',dc:100}];

let locale=loadLocale();
let state=loadState();
let ui=loadUi();
let selectedPrefixes=new Set();
let selectedWords=new Set();
let includesBaseAttack=true;
let editMaximums=false;
let quickEditor=null;
const staticText=[]; const staticAttrs=[];

const $=s=>document.querySelector(s);
const rosterPane=$('#rosterPane'),detailPane=$('#detailPane'),actionPane=$('#actionPane'),guidePane=$('#guidePane');
const rosterList=$('#rosterList'),emptyRoster=$('#emptyRoster'),detailContent=$('#detailContent'),detailEmpty=$('#detailEmpty');
const localeSelect=$('#localeSelect'),characterDialog=$('#characterDialog');

function t(source,vars={}){const out=LOCALES[locale]?.strings?.[source]??source;return out.replace(/\{(\w+)\}/g,(m,k)=>Object.hasOwn(vars,k)?String(vars[k]):m)}
function loadLocale(){const saved=localStorage.getItem(LOCALE_KEY);if(saved&&LOCALES[saved])return saved;return (navigator.language||'en').toLowerCase().startsWith('pl')&&LOCALES.pl?'pl':'en'}
function captureLocale(root){const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while((n=walker.nextNode())){if(n.parentElement?.closest('script,style'))continue;const s=n.nodeValue.trim();if(!s)continue;staticText.push({n,s,lead:n.nodeValue.match(/^\s*/)[0],trail:n.nodeValue.match(/\s*$/)[0]})}root.querySelectorAll?.('[placeholder],[aria-label],[title]').forEach(el=>['placeholder','aria-label','title'].forEach(a=>{if(el.hasAttribute(a))staticAttrs.push({el,a,s:el.getAttribute(a)})}))}
function applyLocale(){document.documentElement.lang=LOCALES[locale]?.htmlLang||locale;staticText.forEach(x=>x.n.nodeValue=x.lead+t(x.s)+x.trail);staticAttrs.forEach(x=>x.el.setAttribute(x.a,t(x.s)));localeSelect.value=locale;renderAll(false)}

function idx(d){return Math.max(0,DICE.indexOf(Number(d)))}
function stepDown(d,n=1){return DICE[Math.max(0,idx(d)-n)]}
function stepUp(d,n=1,max=100){return DICE[Math.min(idx(max),idx(d)+n)]}
function woundsBetween(max,current){return Math.max(0,idx(max)-idx(current))}
function maxHp(c){return ATTRIBUTES.reduce((s,a)=>s+idx(c.maximum[a]),0)}
function currentHp(c){return ATTRIBUTES.reduce((s,a)=>s+idx(c.current[a]),0)}
function effectiveDie(c,a){return stepDown(c.current[a],c.pending[a]||0)}
function healthStatus(c){return c.dead?t('DEAD'):ATTRIBUTES.every(a=>effectiveDie(c,a)===4)?t('0 HP · next hit kills'):t('Alive')}
function hasPending(c){return ATTRIBUTES.some(a=>(c.pending[a]||0)>0)}
function newEquipment(){return {weapons:structuredClone(DEFAULT_WEAPONS),plating:[{type:'medium',equipped:true}]}}
function normalizeCharacter(c){
  const maximum={},current={},pending={};
  ATTRIBUTES.forEach(a=>{maximum[a]=DICE.includes(Number(c.maximum?.[a]))?Number(c.maximum[a]):4;current[a]=DICE.includes(Number(c.current?.[a]))?Number(c.current[a]):maximum[a];current[a]=Math.min(current[a],maximum[a]);pending[a]=Math.min(idx(current[a]),Math.max(0,Math.floor(Number(c.pending?.[a])||0)))});
  return {id:c.id||crypto.randomUUID(),name:c.name||t('Character'),initiative:Number(c.initiative)||0,maximum,current,pending,dead:c.dead===true,equipment:c.equipment||newEquipment()};
}
function loadState(){try{const p=JSON.parse(localStorage.getItem(STORAGE_KEY));if(p?.characters)return {characters:p.characters.map(normalizeCharacter)}}catch(e){console.warn(e)}return {characters:[]}}
function loadUi(){try{return {...{view:'roster',selectedId:null,sortInitiative:false},...JSON.parse(localStorage.getItem(UI_KEY))}}catch{return {view:'roster',selectedId:null,sortInitiative:false}}}
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));localStorage.setItem(UI_KEY,JSON.stringify(ui))}
function getCharacter(id=ui.selectedId){return state.characters.find(c=>c.id===id)||null}
function displayCharacters(){const list=[...state.characters];if(ui.sortInitiative)list.sort((a,b)=>b.initiative-a.initiative||a.name.localeCompare(b.name));return list}

function renderAll(preserve=true){renderRoster();renderDetail();renderComposerCharacters();renderComposer();syncView(false);if(!preserve)return}
function renderRoster(){
  rosterList.replaceChildren();emptyRoster.hidden=state.characters.length>0;
  if(state.characters.length){const labels=document.createElement('div');labels.className='roster-labels';labels.innerHTML=`<span>${t('Init')}</span><span>${t('Character')}</span>${ATTRIBUTES.map(a=>`<span>${a}</span>`).join('')}`;rosterList.append(labels)}
  for(const c of displayCharacters())rosterList.append(renderRosterRow(c));
  const pending=state.characters.reduce((s,c)=>s+ATTRIBUTES.reduce((x,a)=>x+(c.pending[a]||0),0),0);
  $('#roundSummary').textContent=pending?t('{count} pending wounds will apply at round end.',{count:pending}):t('No pending wounds.');
  $('#endRoundButton').disabled=pending===0;
}
function renderRosterRow(c){
  const row=document.createElement('div');row.className='roster-row'+(c.id===ui.selectedId?' selected':'');row.dataset.id=c.id;
  const init=document.createElement('div');init.className='initiative-box';const input=document.createElement('input');input.type='number';input.value=c.initiative;input.setAttribute('aria-label',t('{name} initiative',{name:c.name}));input.addEventListener('click',e=>e.stopPropagation());input.addEventListener('change',()=>{c.initiative=Number(input.value)||0;save();if(ui.sortInitiative)renderRoster()});init.append(input);
  const name=document.createElement('div');name.className='roster-name';name.innerHTML=`<div class="roster-name-line"><strong></strong><button type="button" class="roster-remove" aria-label="${t('Remove from roster')}">×</button></div><span></span>`;name.querySelector('strong').textContent=c.name;name.querySelector('span').textContent=`${currentHp(c)}/${maxHp(c)} HP · ${healthStatus(c)}${hasPending(c)?` · ${t('pending')}`:''}`;
  name.querySelector('.roster-remove').onclick=e=>{e.stopPropagation();removeCharacter(c)};
  row.append(init,name);
  ATTRIBUTES.forEach(a=>{const b=document.createElement('button');b.type='button';b.className='quick-die';if(c.current[a]!==c.maximum[a])b.classList.add('wounded');if(c.pending[a])b.classList.add('pending');if(effectiveDie(c,a)===4)b.classList.add('at-floor');b.innerHTML=`<strong>d${c.current[a]}</strong><small>${c.pending[a]?`→ d${effectiveDie(c,a)}`:a}</small>`;b.setAttribute('aria-label',t('Edit {attribute} for {name}',{attribute:a,name:c.name}));b.addEventListener('click',e=>{e.stopPropagation();openQuickEditor(b,c,a)});row.append(b)});
  row.addEventListener('click',()=>selectCharacter(c.id,true));return row;
}
function openQuickEditor(anchor,c,a){closeQuickEditor();const box=document.createElement('div');box.className='quick-editor';box.innerHTML=`<button type="button" data-op="heal">${t('HEAL')}</button><div><small>${a}</small><strong>d${c.current[a]}</strong><span>${c.pending[a]?`${t('pending')} → d${effectiveDie(c,a)}`:t('current')}</span></div><button type="button" data-op="damage">${t('DMG')}</button>`;document.body.append(box);const r=anchor.getBoundingClientRect();const br=box.getBoundingClientRect();box.style.left=`${Math.max(8,Math.min(innerWidth-br.width-8,r.left+r.width/2-br.width/2))}px`;box.style.top=`${Math.max(8,r.top-br.height-6)}px`;
  const damage=box.querySelector('[data-op="damage"]'),heal=box.querySelector('[data-op="heal"]');damage.disabled=c.dead||effectiveDie(c,a)===4;heal.disabled=c.dead||c.current[a]===c.maximum[a];
  damage.onclick=e=>{e.stopPropagation();if(effectiveDie(c,a)!==4)c.pending[a]=(c.pending[a]||0)+1;save();renderRoster();renderDetail();closeQuickEditor()};
  heal.onclick=e=>{e.stopPropagation();if(c.current[a]!==c.maximum[a])c.current[a]=stepUp(c.current[a],1,c.maximum[a]);save();renderRoster();renderDetail();closeQuickEditor()};quickEditor=box;
}
function closeQuickEditor(){quickEditor?.remove();quickEditor=null}
document.addEventListener('pointerdown',e=>{if(quickEditor&&!quickEditor.contains(e.target))closeQuickEditor()});

function selectCharacter(id,explicit=false){ui.selectedId=id;save();renderRoster();renderDetail();renderComposerCharacters();if(explicit&&matchMedia('(max-width:760px)').matches){setView('detail',true)}}
function renderDetail(){
  const c=getCharacter();detailEmpty.hidden=!!c;detailContent.hidden=!c;if(!c)return;
  const nameInput=$('#detailNameInput');nameInput.value=c.name;nameInput.onchange=()=>{c.name=nameInput.value.trim()||t('Character');nameInput.value=c.name;save();renderRoster();renderComposerCharacters();syncView(false)};
  $('#detailMeta').textContent=`${currentHp(c)} / ${maxHp(c)} HP · ${healthStatus(c)}`;
    $('#damageHelperButton').disabled=c.dead;
  const initInput=$('#detailInitiativeInput');initInput.value=c.initiative;initInput.onchange=()=>{c.initiative=Number(initInput.value)||0;save();renderRoster()};
  $('#detailEndRoundButton').disabled=!state.characters.some(hasPending);
  const stats=$('#detailStats');stats.replaceChildren();ATTRIBUTES.forEach(a=>stats.append(renderStatTile(c,a)));
  renderProfile(c);renderEquipment(c);$('#toggleStatEditButton').textContent=editMaximums?t('Done editing'):t('Edit maximums');
}
function renderStatTile(c,a){const tile=document.createElement('div');tile.className='stat-tile';const pending=c.pending[a]||0;tile.innerHTML=`<span class="stat-name">${a}</span><strong class="stat-die">d${c.current[a]}</strong><span class="stat-max">${pending?`${t('pending')} → d${effectiveDie(c,a)}`:`${t('max')} d${c.maximum[a]}`}</span><div class="stat-controls"><button type="button" data-heal>${t('HEAL')}</button><button type="button" data-damage>${t('DMG')}</button></div>`;
  tile.querySelector('[data-damage]').disabled=c.dead||effectiveDie(c,a)===4;tile.querySelector('[data-heal]').disabled=c.dead||c.current[a]===c.maximum[a];
  tile.querySelector('[data-damage]').onclick=()=>{if(effectiveDie(c,a)!==4)c.pending[a]=pending+1;save();renderRoster();renderDetail()};
  tile.querySelector('[data-heal]').onclick=()=>{if(c.current[a]!==c.maximum[a])c.current[a]=stepUp(c.current[a],1,c.maximum[a]);save();renderRoster();renderDetail()};
  if(editMaximums){const s=document.createElement('select');s.className='stat-edit-select';DICE.forEach(d=>s.add(new Option(`d${d}`,String(d),false,d===c.maximum[a])));s.onchange=()=>{const old=c.maximum[a],next=Number(s.value);c.maximum[a]=next;if(idx(c.current[a])>idx(next))c.current[a]=next;else if(c.current[a]===old)c.current[a]=next;c.pending[a]=Math.min(c.pending[a]||0,idx(c.current[a]));save();renderRoster();renderDetail()};tile.append(s)}return tile}
function platingProfile(c){const items=(c.equipment.plating||[]).filter(x=>x.equipped!==false).map(x=>PLATING_TYPES[x.type]||PLATING_TYPES.medium);if(!items.length)return {braceGuarantee:0,dodgeLimit:0};return {braceGuarantee:Math.max(...items.map(x=>x.braceGuarantee)),dodgeLimit:Math.min(...items.map(x=>x.dodgeLimit))}}
function primaryWeapon(c){return (c.equipment.weapons||[]).find(x=>x.equipped!==false)||null}
function renderProfile(c){const p=platingProfile(c),w=primaryWeapon(c);const cards=[['HP',`${currentHp(c)}/${maxHp(c)}`,hasPending(c)?t('Pending wounds queued'):t('Stable')],['Brace guarantee',p.braceGuarantee||'—',t('Highest equipped guarantee')],['Dodge limit',p.dodgeLimit||'—',t('Lowest equipped limit')],['Weapon impact',w?w.impact||0:'—',w?t(w.name):t('No weapon')]];const root=$('#combatProfile');root.replaceChildren(...cards.map(([label,value,note])=>{const d=document.createElement('div');d.className='profile-card';d.innerHTML=`<span>${t(label)}</span><strong>${value}</strong><small>${note}</small>`;return d}))}
function renderEquipment(c){const root=$('#equipmentList');root.replaceChildren();(c.equipment.weapons||[]).forEach((w,i)=>root.append(renderWeapon(c,w,i)));(c.equipment.plating||[]).forEach((p,i)=>root.append(renderPlating(c,p,i)))}
function equipmentField(label,control,wide=false){const l=document.createElement('label');l.className='field-label'+(wide?' wide-field':'');const s=document.createElement('span');s.textContent=t(label);l.append(s,control);return l}
function selectDice(value){const s=document.createElement('select');DICE.forEach(d=>s.add(new Option(`d${d}`,String(d),false,d===Number(value))));return s}
function renderWeapon(c,w,i){const card=document.createElement('article');card.className='equipment-card';const head=document.createElement('header');const title=document.createElement('strong');title.textContent=t('Weapon');const remove=document.createElement('button');remove.type='button';remove.className='remove-equipment';remove.textContent='×';remove.setAttribute('aria-label',t('Remove weapon'));remove.onclick=()=>{c.equipment.weapons.splice(i,1);save();renderDetail();renderComposerCharacters();renderComposer()};head.append(title,remove);const fields=document.createElement('div');fields.className='equipment-fields';
  const name=document.createElement('input');name.value=w.name;name.onchange=()=>{w.name=name.value.trim()||t('Weapon');save();renderDetail();renderComposerCharacters()};
  const weaponClass=document.createElement('select');Object.entries(WEAPON_CLASSES).forEach(([key,def])=>weaponClass.add(new Option(t(def.label),key,false,key===(w.weaponClass||'light'))));weaponClass.onchange=()=>{w.weaponClass=weaponClass.value;const opts=WEAPON_CLASSES[w.weaponClass].accuracyOptions;if(!opts.includes(w.accuracy))w.accuracy=opts[0];save();renderDetail();renderComposer()};
  const acc=document.createElement('select');WEAPON_CLASSES[w.weaponClass||'light'].accuracyOptions.forEach(a=>acc.add(new Option(a,a,false,a===w.accuracy)));acc.onchange=()=>{w.accuracy=acc.value;save();renderProfile(c);renderComposer()};
  const impact=document.createElement('input');impact.type='number';impact.min='0';impact.max='30';impact.value=w.impact??6;impact.onchange=()=>{w.impact=Math.max(0,Number(impact.value)||0);save();renderProfile(c);renderComposer()};
  fields.append(equipmentField('Name',name,true),equipmentField('Class',weaponClass),equipmentField('Accuracy',acc),equipmentField('Impact',impact));card.append(head,fields);return card}
function renderPlating(c,p,i){const card=document.createElement('article');card.className='equipment-card';const head=document.createElement('header');const title=document.createElement('strong');title.textContent=t('Plating');const remove=document.createElement('button');remove.type='button';remove.className='remove-equipment';remove.textContent='×';remove.setAttribute('aria-label',t('Remove plating'));remove.onclick=()=>{c.equipment.plating.splice(i,1);save();renderDetail()};head.append(title,remove);const fields=document.createElement('div');fields.className='equipment-fields';
  const type=document.createElement('select');Object.entries(PLATING_TYPES).forEach(([key,def])=>type.add(new Option(t(def.label),key,false,key===(p.type||'medium'))));type.onchange=()=>{p.type=type.value;save();renderDetail()};
  const stats=PLATING_TYPES[p.type]||PLATING_TYPES.medium;
  const brace=document.createElement('input');brace.value=String(stats.braceGuarantee);brace.disabled=true;
  const dodge=document.createElement('input');dodge.value=String(stats.dodgeLimit);dodge.disabled=true;
  fields.append(equipmentField('Type',type,true),equipmentField('Brace guarantee',brace),equipmentField('Dodge limit',dodge));card.append(head,fields);return card}

function renderComposerCharacters(){const s=$('#composerCharacter');const prior=s.value||ui.selectedId||'';s.replaceChildren(new Option(t('Generic / no character'),''));state.characters.forEach(c=>s.add(new Option(c.name,c.id,false,c.id===prior)));if([...s.options].some(o=>o.value===prior))s.value=prior;renderComposerWeapons()}
function renderComposerWeapons(){const c=getCharacter($('#composerCharacter').value);const s=$('#composerWeapon');const prior=s.value;s.replaceChildren(new Option(t('Unarmed / generic'),''));(c?.equipment.weapons||[]).forEach((w,i)=>s.add(new Option(w.name,String(i))));if([...s.options].some(o=>o.value===prior))s.value=prior}
function selectedWeapon(){const c=getCharacter($('#composerCharacter').value);const i=Number($('#composerWeapon').value);return c&&$('#composerWeapon').value!==''?c.equipment.weapons[i]:null}
function composerHasAttackShape(words=selectedWordData()){return words.some(w=>w.category==='shape'&&w.delivery==='primary-attack')}
function composerHasBaseAttack(words=selectedWordData()){return includesBaseAttack&&!composerHasAttackShape(words)}
function composerAllowsPrefixes(){return composerHasBaseAttack()||composerHasAttackShape()}
function renderPrefixes(){const root=$('#prefixGrid');root.replaceChildren();Object.entries(PREFIXES).forEach(([key,p])=>{const b=document.createElement('button');b.type='button';b.className='choice-card';b.dataset.key=key;b.disabled=!composerAllowsPrefixes()&&!selectedPrefixes.has(key);b.title=[t('Prefixes modify a Base Attack or an attack-like Shape.'),...p.effects.map(effect=>t(effect)),key==='knockback'?t('On a failed enemy Brace, knock the target back Potential × 5 m. The normal damage chain is unchanged.'):''].filter(Boolean).join(' ');b.setAttribute('aria-pressed',String(selectedPrefixes.has(key)));b.innerHTML=`<strong>${t(p.label)}</strong><span>1 AP · ${p.potential?`+${p.potential} ${t('potential')}`:t('multi-target')}</span>`;b.onclick=()=>{selectedPrefixes.has(key)?selectedPrefixes.delete(key):selectedPrefixes.add(key);renderComposer()};root.append(b)})}
function selectedWordData(){const out=[];for(const cat of Object.keys(WORDS))for(const w of WORDS[cat])if(selectedWords.has(`${cat}:${w.id}`))out.push({...w,category:cat});return out}
function renderWords(){const root=$('#wordCategories');root.replaceChildren();for(const [cat,words] of Object.entries(WORDS)){const sec=document.createElement('section');sec.className='word-category';const h=document.createElement('h3');h.textContent=t(cat==='source'?'Sources':cat==='shape'?'Shapes':'Mastery');const grid=document.createElement('div');grid.className='word-grid';words.forEach(w=>{const key=`${cat}:${w.id}`,b=document.createElement('button');b.type='button';b.className='word-button';b.setAttribute('aria-pressed',String(selectedWords.has(key)));b.innerHTML=`<strong>${t(w.name)}</strong><b>${w.word}</b><small>${w.mana?`${w.mana} ${t('Mana')}`:w.dust?`${w.dust} ${t('Dust')}`:t('No energy')}</small>`;b.title=[...(Array.isArray(w.effects)?w.effects:Object.values(w.effects)),w.interactions].map(t).join(' ');b.onclick=()=>{selectedWords.has(key)?selectedWords.delete(key):selectedWords.add(key);renderComposer();renderWords()};grid.append(b)});sec.append(h,grid);root.append(sec)}}
function resolveWordComposition(words,hasBaseAttack){
  const sources=words.filter(x=>x.category==='source'),shapes=words.filter(x=>x.category==='shape'),mastery=words.filter(x=>x.category==='mastery');
  const primaries=shapes.filter(x=>x.delivery==='primary-attack'),primary=primaries[0]||null,containers=shapes.filter(x=>x.delivery==='container'||x.delivery==='area');
  const hearing=mastery.find(x=>x.delivery==='mastery-hearing'),diagnostics=[];
  if(primaries.length>1)diagnostics.push(t('Competing primary delivery Shapes: {selected}. Tracker ruling: {winner} wins by stable catalog priority; the others modify the endpoint only where their interaction permits.',{selected:primaries.map(x=>t(x.name)).join(', '),winner:t(primary.name)}));
  if(shapes.some(x=>['spiral','flat'].includes(x.id))&&shapes.length===1)diagnostics.push(t('{shape} requires another Shape to modify.',{shape:t(shapes[0].name)}));
  if(sources.some(x=>x.id==='echoes')&&words.length===1)diagnostics.push(t('Echoes requires an identifiable earlier spell trace; choose one at the table.'));
  let mode='touch';if(hasBaseAttack)mode='smite';else if(primary)mode='attack';else if(containers.length)mode='area';
  let delivery,targets,resolution;
  if(hasBaseAttack){delivery=t('Weapon or unarmed hit carries the selected Sources.');targets=t('One attack target; weapon range applies.');resolution=t('Roll weapon accuracy. Source Smite is part of that hit.');}
  else if(hearing){delivery=t('Power Word delivers the payload through hearing.');targets=t('Anything that can hear within audible reach; compatible Shapes manifest on each listener.');resolution=t('Targets use area resistance; no spell-accuracy roll unless a carried primary Shape specifically attacks one target.');}
  else if(primary){delivery=t('{shape} is the primary delivery: {target}, range {range}.',{shape:t(primary.name),target:t(primary.target),range:t(primary.range)});targets=containers.length?t('Attack the primary target, then place {areas} at the target or impact point; occupants in those footprints are also affected.',{areas:containers.map(x=>`${t(x.name)} (${t(x.area)})`).join(', ')}):t('{target}; {area}.',{target:t(primary.target),area:t(primary.area)});resolution=containers.length?t('Roll spell accuracy for the primary target. Other occupants of a manifested area use resistance DC {difficulty} {dc}.',{difficulty:t(CASTING_DIFFICULTIES[Math.min(words.length-1,CASTING_DIFFICULTIES.length-1)].name),dc:CASTING_DIFFICULTIES[Math.min(words.length-1,CASTING_DIFFICULTIES.length-1)].dc}):t('Roll spell accuracy against the primary target’s defense.');}
  else if(containers.length){const difficulty=CASTING_DIFFICULTIES[Math.min(words.length-1,CASTING_DIFFICULTIES.length-1)];delivery=t('Area/container Shapes place the payload directly; no attack roll.');targets=containers.map(x=>`${t(x.name)}: ${t(x.area)}, ${t(x.range)}, ${t(x.duration)}`).join(' · ');resolution=t('Each affected target makes area resistance at {difficulty} {dc}. Resistance difficulty uses total selected Word count ({count}), not AP or prefix count.',{difficulty:t(difficulty.name),dc:difficulty.dc,count:words.length});}
  else{delivery=t('Somatic touch delivers an unshaped Source or utility Word.');targets=t('One touched target.');resolution=t('Willing target: no roll. Harmful use follows target defense or resistance as agreed at the table.');}
  return {sources,shapes,mastery,primaries,primary,containers,mode,diagnostics,delivery,targets,resolution,hasArea:!!hearing||containers.length>0};
}
function renderComposer(){renderPrefixes();const words=selectedWordData(),hasAttackShape=composerHasAttackShape(words),hasBaseAttack=composerHasBaseAttack(words);const resolved=resolveWordComposition(words,hasBaseAttack);const c=getCharacter($('#composerCharacter')?.value),w=hasBaseAttack?selectedWeapon():null;const prefixKeys=Object.keys(PREFIXES).filter(k=>selectedPrefixes.has(k));const invalidPrefixes=prefixKeys.length>0&&!composerAllowsPrefixes();const hasAction=hasBaseAttack||words.length>0;const valid=hasAction&&!invalidPrefixes;const isSmite=hasBaseAttack&&words.length===1&&words[0].category==='source';const wordAp=words.length-(isSmite?1:0);const ap=(hasBaseAttack?1:0)+prefixKeys.length+wordAp;const basePotential=hasBaseAttack?BASE_ATTACK_POTENTIAL:0;const mana=words.reduce((s,x)=>s+(x.mana||0),0),dust=words.reduce((s,x)=>s+(x.dust||0),0);const prefixPotential=prefixKeys.reduce((s,k)=>s+PREFIXES[k].potential,0);const potential=basePotential+mana+dust+prefixPotential;
  $('#composerWeapon').disabled=!hasBaseAttack;const baseButton=$('#includeAttackButton');baseButton.disabled=hasAttackShape;baseButton.setAttribute('aria-pressed',String(hasBaseAttack));baseButton.classList.toggle('active',hasBaseAttack);
  const baseNote=hasAttackShape?t('Attack-like Shapes replace Base Attack: no base AP/potential, weapon accuracy/Impact, or Smite discount.')+' '+t(includesBaseAttack?'Remove the last attack-like Shape to restore your saved Base Attack: on.':'Remove the last attack-like Shape to restore your saved Base Attack: off.'):t('Base Attack preference is remembered while attack-like Shapes replace it.');baseButton.title=baseNote;$('#baseAttackNote').textContent=baseNote;
  const readable=x=>t(x.id==='thunder'&&x.category==='source'?'Lightning':x.name);const parts=prefixKeys.map(k=>t(PREFIXES[k].label));if(hasBaseAttack){parts.push(w?t('Weapon Attack ({weapon})',{weapon:t(w.name)}):t('Attack'));if(resolved.sources.length)parts.push(t('of {sources}',{sources:resolved.sources.map(readable).join('/')}));parts.push(...words.filter(x=>x.category!=='source').map(readable))}else parts.push(...words.map(readable));
  $('#actionName').textContent=invalidPrefixes?t('Choose an attack for these prefixes'):parts.join(' ')||t('Choose components');const incantation=[...prefixKeys.map(k=>PREFIXES[k].word),...words.map(x=>x.word)].join(' ');$('#actionIncantation').hidden=!valid||!incantation;$('#actionIncantation').textContent=valid&&incantation?t('Alternative incantation (tracker flavor, not canonical): {name}',{name:incantation}):'';
  let accuracy='—';if(w)accuracy=c?`${w.accuracy} d${c.current[w.accuracy]}`:w.accuracy;else if(!hasBaseAttack&&resolved.primary){const spellAttr=c&&idx(c.current.AUR)>idx(c.current.INT)?'AUR':'INT';accuracy=c?`${spellAttr} d${c.current[spellAttr]}`:t('INT or AUR, whichever is higher')}else if(!hasBaseAttack&&resolved.hasArea)accuracy=t('Area resistance');
  const metrics=[['AP',valid?ap:'—'],['Potential',valid?potential:'—'],['Accuracy',valid?accuracy:'—']];$('#actionMetrics').replaceChildren(...metrics.map(([k,v])=>{const d=document.createElement('div');d.className='metric';d.innerHTML=`<span>${t(k)}</span><strong>${v}</strong>`;return d}));
  const effects=[];if(invalidPrefixes)effects.push(t('Prefixes need a Base Attack or an attack-like Shape. Add one, or remove the prefixes; no totals are shown until then.'));if(valid&&w)effects.push(t('Impact: {value}.',{value:w.impact??6}));for(const k of valid?prefixKeys:[])effects.push(...PREFIXES[k].effects.map(effect=>t(effect)));if(valid&&selectedPrefixes.has('dashing'))effects.push(t('Dashing movement: up to {meters} m.',{meters:potential*5}));if(valid&&selectedPrefixes.has('knockback'))effects.push(t('On a failed enemy Brace, knock the target back {meters} m (Potential × 5). The normal damage chain is unchanged.',{meters:potential*5}));if(valid&&hasBaseAttack&&resolved.sources.length>1)effects.push(t('Multiple Sources in a weapon or unarmed combination each cost 1 AP; slash-separated names do not grant a Smite discount.'));if(valid&&words.length){effects.push(`${t('Resources')}: ${[mana?`${mana} ${t('Mana')}`:'',dust?`${dust} ${t('Dust')}`:''].filter(Boolean).join(' · ')||t('None')}`);effects.push(t('Tracker ruling: potential = base {base} + prefixes {prefixes} + Mana {mana} + Dust {dust} = {total}.',{base:basePotential,prefixes:prefixPotential,mana,dust,total:potential}));const energy=mana+dust;if(energy>=3){let i=Math.min(energy-3,CASTING_DIFFICULTIES.length-1);if(resolved.mastery.some(x=>x.id==='hold'))i=Math.max(0,i-1);effects.push(`${t('Caster casting check')}: ${t(CASTING_DIFFICULTIES[i].name)} ${CASTING_DIFFICULTIES[i].dc}`)}else effects.push(t('Caster casting check: none (fewer than 3 energy spent).'));if(isSmite)effects.push(t('Source Smite costs Mana but no additional AP.'))}if(valid&&ap>3)effects.push(t('{turns}-turn action; charge before release.',{turns:Math.ceil(ap/3)}));$('#actionEffects').replaceChildren(...effects.map(x=>{const li=document.createElement('li');li.textContent=x;return li}));
  const setText=(id,text)=>{const node=$(id);if(node)node.textContent=valid?text:'—'};setText('#deliverySummary',resolved.delivery);setText('#targetsSummary',resolved.targets);setText('#resolutionSummary',resolved.resolution);
  const setList=(id,items)=>{const node=$(id);if(node)node.replaceChildren(...items.map(x=>{const li=document.createElement('li');li.textContent=t(x);return li}))};setList('#sourceEffects',valid?resolved.sources.map(x=>`${t(x.name)}: ${t(x.effects[resolved.mode]||x.effects.touch)} ${t('Duration')}: ${t(x.duration)} ${t('Tracker ruling.')}`):[]);setList('#shapeInteractions',valid?resolved.shapes.map(x=>`${t(x.name)}: ${t(x.interactions)}`):[]);setList('#masteryEffects',valid?resolved.mastery.flatMap(x=>[...x.effects.map(effect=>`${t(x.name)}: ${t(effect)}`),`${t(x.name)} — ${t(x.interactions)}`]):[]);setList('#composerDiagnostics',resolved.diagnostics);
}

function setView(view,explicit=true){ui.view=view;save();syncView(explicit)}
function syncView(explicit=false){const mobile=matchMedia('(max-width:760px)').matches;const single=state.characters.length===1;let view=ui.view==='detail'?'detail':ui.view;if(mobile&&single&&view==='roster')view='detail';rosterPane.hidden=view!=='roster'&&!(view==='detail'&&!mobile);detailPane.hidden=view!=='detail'&&view!=='roster';actionPane.hidden=view!=='action';guidePane.hidden=view!=='guide';document.body.classList.toggle('single-character',single);if(mobile){rosterPane.classList.toggle('mobile-hidden',view!=='roster');detailPane.classList.toggle('mobile-hidden',view!=='detail')}else{rosterPane.classList.remove('mobile-hidden');detailPane.classList.remove('mobile-hidden')}
  document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.view===((view==='detail'||(single&&ui.view==='roster'))?'roster':view)));$('#headerTitle').textContent=t(view==='action'?'Action Composer':view==='guide'?'Combat Guide':view==='detail'?(getCharacter()?.name||'Character'):'Roster');if(explicit)window.scrollTo({top:0,behavior:'auto'})}

function removeCharacter(c){if(!c||!confirm(t('Remove {name} from roster?',{name:c.name})))return;state.characters=state.characters.filter(x=>x.id!==c.id);if(ui.selectedId===c.id)ui.selectedId=state.characters[0]?.id||null;if(!state.characters.length)ui.view='roster';save();renderAll();}
function openCharacterDialog(){const tpl=TEMPLATES[0];populateCreator(tpl);characterDialog.showModal()}
function populateCreator(tpl){$('#newCharacterName').value=tpl.id==='blank'?'':t(tpl.name);$('#newCharacterCount').value='1';const root=$('#newCharacterStats');root.replaceChildren();ATTRIBUTES.forEach((a,i)=>{const s=selectDice(tpl.stats[i]);s.name=a;root.append(equipmentField(a,s))});$('#templateGrid').querySelectorAll('.template-button').forEach(b=>b.classList.toggle('active',b.dataset.id===tpl.id))}
function renderTemplates(){const root=$('#templateGrid');root.replaceChildren(...TEMPLATES.map(tpl=>{const b=document.createElement('button');b.type='button';b.className='template-button';b.dataset.id=tpl.id;b.innerHTML=`<strong>${t(tpl.name)}</strong><span>${tpl.stats.map(x=>`d${x}`).join(' · ')}</span>`;b.onclick=()=>populateCreator(tpl);return b}))}

$('#addButton').onclick=openCharacterDialog;$('#rosterAddButton').onclick=openCharacterDialog;$('#cancelCharacterButton').onclick=()=>characterDialog.close();
$('#characterForm').addEventListener('submit',e=>{e.preventDefault();const base=$('#newCharacterName').value.trim()||t('Character');const count=Math.min(20,Math.max(1,Number($('#newCharacterCount').value)||1));const maximum={};ATTRIBUTES.forEach(a=>maximum[a]=Number(e.target.elements[a].value));for(let i=0;i<count;i++){const name=count>1?`${base} ${i+1}`:base;state.characters.push(normalizeCharacter({name,initiative:0,maximum,current:{...maximum},pending:{},equipment:newEquipment()}))}if(!ui.selectedId)ui.selectedId=state.characters[0]?.id||null;save();characterDialog.close();renderAll()});
$('#sortInitiativeButton').onclick=()=>{ui.sortInitiative=!ui.sortInitiative;save();$('#sortInitiativeButton').textContent=t(ui.sortInitiative?'Use roster order':'Sort initiative');renderRoster()};
$('#endRoundButton').onclick=()=>{if(!state.characters.some(hasPending))return;if(!confirm(t('Apply all pending wounds?')))return;state.characters.forEach(c=>ATTRIBUTES.forEach(a=>{c.current[a]=stepDown(c.current[a],c.pending[a]||0);c.pending[a]=0}));save();renderAll()};
$('#backToRosterButton').onclick=()=>setView('roster',true);$('#detailEndRoundButton').onclick=()=>$('#endRoundButton').click();$('#fullHpButton').onclick=()=>{const c=getCharacter();if(!c||!confirm(t('Reset to full HP, clear pending wounds, and remove death? This is a GM override, not a rest.')))return;ATTRIBUTES.forEach(a=>{c.current[a]=c.maximum[a];c.pending[a]=0});c.dead=false;save();renderAll()};
$('#toggleStatEditButton').onclick=()=>{editMaximums=!editMaximums;renderDetail()};
$('#addWeaponButton').onclick=()=>{const c=getCharacter();if(!c)return;c.equipment.weapons.push({name:t('Weapon'),weaponClass:'light',accuracy:'STR',impact:6,equipped:true});save();renderDetail();renderComposerCharacters()};
$('#addArmorButton').onclick=()=>{const c=getCharacter();if(!c)return;c.equipment.plating.push({type:'medium',equipped:true});save();renderDetail()};
$('#deleteCharacterButton').onclick=()=>removeCharacter(getCharacter());
$('#composerCharacter').onchange=()=>{const id=$('#composerCharacter').value;if(id){ui.selectedId=id;save();renderRoster();renderDetail()}renderComposerWeapons();renderComposer()};$('#composerWeapon').onchange=renderComposer;$('#includeAttackButton').onclick=()=>{includesBaseAttack=!includesBaseAttack;renderComposer()};$('#clearComposerButton').onclick=()=>{selectedPrefixes.clear();selectedWords.clear();renderWords();renderComposer()};$('#clearWordsButton').onclick=()=>{selectedWords.clear();renderWords();renderComposer()};
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>setView(b.dataset.view,true));localeSelect.onchange=()=>{locale=localeSelect.value;localStorage.setItem(LOCALE_KEY,locale);applyLocale();renderTemplates();renderWords()};
matchMedia('(max-width:760px)').addEventListener('change',()=>syncView(false));

captureLocale(document.documentElement);localeSelect.value=locale;applyLocale();renderTemplates();renderWords();renderAll(false);
