'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {spawnSync} = require('node:child_process');

for (const width of [1280, 390]) test(`Chromium smoke (${width}px): damage, cumulative recovery, composer, locale and persistence`, () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(),'sigil-sheet-'));
  try {
    const checks = `
      const check = (condition, message) => {if (!condition) throw new Error(message)};
      const click = selector => {const el=document.querySelector(selector);check(el,selector);el.click()};
      const input = (selector,value) => {const el=document.querySelector(selector);el.value=value;el.dispatchEvent(new Event('input',{bubbles:true}))};
      window.confirm=()=>true;
      state.characters=[normalizeCharacter({id:'test',name:'Test <safe>',maximum:{STR:6,DEX:6,CON:6,INT:4,SEN:4,AUR:4}})];
      ui.selectedId='test'; renderAll();
      check(document.querySelector('#detailMeta').textContent.includes('Alive'),'alive at startup');
      click('#damageHelperButton');
      const damageForm=document.querySelector('dialog[open] form');
      check(damageForm.querySelectorAll('input').length===1&&damageForm.querySelector('[name="amount"]'),'damage helper has only the amount input');
      check(!damageForm.querySelector('input[type="checkbox"], select, [data-attributes]'),'automatic damage has no eligibility or Precision controls');
      check(damageForm.querySelector('[type="submit"]').disabled,'damage requires preview');
      const beforeDamage=JSON.stringify(getCharacter());
      input('[name="amount"]','1');click('dialog[open] [data-preview]');
      check(JSON.stringify(getCharacter())===beforeDamage,'damage preview does not mutate character');
      input('[name="amount"]','5');
      check(damageForm.querySelector('[type="submit"]').disabled&&damageForm.querySelector('[data-result]').textContent==='','changing amount invalidates previous allocation');
      click('dialog[open] [data-preview]');
      check(document.querySelector('[data-result]').textContent.includes('Ignored overflow: 2.'),'overflow preview');
      click('dialog[open] [type="submit"]');
      check(!getCharacter().dead&&hasPending(getCharacter()),'queued not dead');
      check(document.querySelector('#detailMeta').textContent.includes('next hit kills'),'pending critical status');
      click('#endRoundButton');
      check(currentHp(getCharacter())===0&&!getCharacter().dead,'0 HP survives');
      click('#damageHelperButton'); click('dialog[open] [data-preview]'); click('dialog[open] [type="submit"]');
      check(getCharacter().dead,'next hit kills');
      check(loadState().characters[0].dead,'death persisted');
      click('#fullHpButton');
      check(!getCharacter().dead&&currentHp(getCharacter())===3,'GM reset');
      const c=getCharacter(); c.maximum.INT=6;c.current.CON=4;renderAll();
      click('#recoveryButton');

      const el = selector => document.querySelector(selector);
      const heal = (a,n=1) => {for(let i=0;i<n;i++) click('#recoveryHeal-'+a)};
      const die = a => el('#recoveryStats [data-attribute="'+a+'"] .stat-die').textContent;
      const layout = language => {
        const dialog=el('#recoveryDialog'), row=el('.recovery-stage-row');
        check(dialog.querySelectorAll('input[type="checkbox"]').length===3,language+' exactly three stage checkboxes');
        check(!dialog.querySelector('input[type="number"], #recoveryApproval, [id^="recoveryBudget"], [id^="recoveryAllocation"]'),language+' no grants or editable budgets');
        check(dialog.querySelectorAll('#recoveryStats .stat-tile').length===6,language+' one six-stat grid');
        const toggles=[...row.querySelectorAll('.recovery-stage-toggle')].map(node=>node.getBoundingClientRect());
        check(toggles.length===3&&toggles.every(rect=>Math.abs(rect.top-toggles[0].top)<1),language+' stages remain one row');
        for(const node of [document.documentElement,dialog,dialog.querySelector('form'),row,el('#recoveryStats')]) {
          check(node.scrollWidth<=node.clientWidth+1,language+' no horizontal overflow: '+node.tagName+'.'+node.className);
        }
        const bounds=dialog.getBoundingClientRect();
        check(bounds.left>=0&&bounds.right<=innerWidth+1,language+' dialog within viewport');
        const tiles=[...dialog.querySelectorAll('.stat-tile')].map(node=>node.getBoundingClientRect());
        check(tiles.filter(rect=>Math.abs(rect.top-tiles[0].top)<1).length===(${width}===390?3:6),language+' responsive stat columns');
      };
      layout('EN');
      check(el('#recoveryStage-encounter').parentElement.textContent==='Second Wind','short stage label');
      check(el('#recoveryApply').disabled,'empty recovery disabled');
      check(el('#recoveryWaste-encounter').textContent==='1/1 left','automatic budget');
      check(el('#recoveryWaste-short').textContent==='Not selected','unselected stage');
      const persistedBefore=JSON.stringify(loadState()), characterBefore=JSON.stringify(c);
      heal('CON');
      check(die('CON')==='d6'&&!el('#recoveryUndo-CON').disabled,'HEAL preview and undo');
      check(el('#recoveryHeal-CON').disabled,'HEAL at maximum disabled');
      check(!el('#recoveryApply').disabled,'recovery valid without approval');
      check(JSON.stringify(c)===characterBefore&&JSON.stringify(loadState())===persistedBefore,'preview does not mutate or persist');
      click('#recoveryUndo-CON');
      check(die('CON')==='d4'&&el('#recoveryApply').disabled&&el('#recoveryUndo-CON').disabled,'undo clears preview');
      check(JSON.stringify(c)===characterBefore&&JSON.stringify(loadState())===persistedBefore,'undo does not mutate or persist');
      heal('CON');click('#recoveryDialog .modal-actions [type="button"]');
      check(!el('#recoveryDialog').open,'cancel closes recovery');
      click('#recoveryButton');
      check(die('CON')==='d4'&&el('#recoveryApply').disabled,'cancel and reopen discard allocation');
      check(JSON.stringify(c)===characterBefore&&JSON.stringify(loadState())===persistedBefore,'cancel does not persist');
      heal('CON');click('#recoveryApply');
      check(c.current.CON===6,'recovery applied');
      check(loadState().characters[0].current.CON===6,'recovery persisted');
      ATTRIBUTES.forEach(a=>{c.maximum[a]=8;c.current[a]=4});save();renderAll();
      const cumulativeBefore=JSON.stringify(c), cumulativePersisted=JSON.stringify(loadState());
      click('#recoveryButton');
      for(const a of ['STR','DEX','AUR','SEN']) check(el('#recoveryHeal-'+a).disabled,'unselected eligibility '+a);
      click('#recoveryStage-long');
      check(el('#recoveryStage-short').checked&&el('#recoveryStage-encounter').checked,'Long includes both prerequisites');
      check(el('#recoverySummary').textContent==='Recovery: 0/12 tiers · Unused: 12','cumulative automatic budget');
      heal('CON');heal('INT');heal('AUR',2);heal('SEN');heal('STR',2);heal('DEX',2);
      check(el('#recoveryHeal-SEN').disabled,'Short budget exhausted below SEN maximum');
      check(el('#recoveryHeal-STR').disabled&&el('#recoveryHeal-DEX').disabled,'Long maxima enforced with unused budget');
      check(el('#recoveryWaste-encounter').textContent==='1/3 left','Second Wind waste');
      check(el('#recoveryWaste-long').textContent==='2/6 left','Long waste');
      check(el('#recoverySummary').textContent==='Recovery: 9/12 tiers · Unused: 3','combined allocation and waste');
      click('#recoveryStage-short');
      check(!el('#recoveryStage-long').checked,'removing Short removes Long');
      for(const a of ['STR','DEX','AUR','SEN']) check(die(a)==='d4'&&el('#recoveryUndo-'+a).disabled&&el('#recoveryHeal-'+a).disabled,'later allocation cleared '+a);
      check(die('CON')==='d6'&&die('INT')==='d6','earlier allocations retained');
      click('#recoveryStage-long');
      heal('AUR',2);heal('SEN');heal('STR',2);heal('DEX',2);
      check(JSON.stringify(c)===cumulativeBefore&&JSON.stringify(loadState())===cumulativePersisted,'cumulative preview remains unpersisted');
      click('#recoveryApply');
      check(currentHp(c)===9&&maxHp(c)===12,'separate budgets apply without adding waste');
      c.equipment.weapons[0].name='Spear';renderAll();setView('action');
      document.querySelector('#composerWeapon').value='0';
      selectedPrefixes=new Set(['power','precision']);selectedWords=new Set(['source:thunder']);includesBaseAttack=true;renderComposer();renderWords();
      check(document.querySelector('#actionName').textContent==='Precision Power Weapon Attack (Spear) of Lightning','clean weapon name');
      selectedPrefixes.delete('power');selectedWords.add('source:fire');selectedWords.add('shape:bolt');renderComposer();renderWords();
      check(document.querySelector('#actionName').textContent==='Precision Lightning Fire Bolt','clean spell name');
      check(document.querySelector('#actionMetrics strong').textContent==='4','example costs 4 AP');
      check(document.querySelector('#composerWeapon').disabled&&document.querySelector('#includeAttackButton').disabled,'Shape excludes weapon and base');
      check(!document.querySelector('#actionEffects').textContent.includes('Impact:'),'Shape ignores weapon impact');
      check(!document.querySelector('#actionIncantation').hidden,'alternative incantation visible');
      click('#clearWordsButton');
      check(!document.querySelector('#includeAttackButton').disabled&&document.querySelector('#includeAttackButton').getAttribute('aria-pressed')==='true','base preference restored');
      click('#prefixGrid [data-key="disarming"]');click('#prefixGrid [data-key="knockback"]');
      check(document.querySelector('#actionEffects').textContent.includes('25 m'),'knockback uses total potential');
      check(document.querySelector('#actionEffects').textContent.includes('drops a held item'),'Disarming effect');
      check([...document.querySelectorAll('#guidePane dd')].some(el=>el.textContent.startsWith('1 AP · +1 potential. On a failed enemy Brace, knock')),'complete Knockback guide text');
      localeSelect.value='pl';localeSelect.onchange();
      check(document.querySelector('#damageHelperButton').textContent==='Losowanie ran dla MG','Polish label');
      click('#recoveryButton');
      check(document.querySelector('#recoveryTitle').textContent.includes(c.name),'reopened localized recovery');
      check(document.querySelector('#recoveryApply').disabled,'reopened allocation empty');
            layout('PL');
            check(el('#recoveryStage-encounter').checked&&!el('#recoveryStage-short').checked&&!el('#recoveryStage-long').checked,'reopened stage selection reset');
            for(const a of ATTRIBUTES) check(el('#recoveryUndo-'+a).disabled&&die(a)==='d'+c.current[a],'reopened preview matches character '+a);
      check(document.querySelector('#recoveryStage-long').parentElement.textContent.includes('Długi odpoczynek'),'Polish stage label');
      check(loadState().characters[0].current.DEX===8,'cumulative recovery persisted');
      click('#recoveryDialog .modal-actions [type="button"]');
      c.current={STR:10,DEX:6,CON:4,INT:4,SEN:4,AUR:4};c.maximum.STR=12;
      c.pending={STR:1,DEX:1,CON:0,INT:0,SEN:0,AUR:0};save();renderAll();
      const pendingBefore=JSON.stringify(c);
      click('#damageHelperButton');
      input('dialog[open] [name="amount"]','5');click('dialog[open] [data-preview]');
      const pendingResult=el('dialog[open] [data-result]').textContent;
      check(pendingResult.includes('STR: −2')&&!pendingResult.includes('DEX:'),'automatically repeats the only attribute with remaining capacity');
      check(pendingResult.includes('Pominięty nadmiar: 3.'),'pending wounds counted in overflow');
      check(JSON.stringify(c)===pendingBefore,'pending-aware preview remains non-mutating');
      check(el('dialog[open] [type="submit"]').textContent==='Zastosuj obrażenia','Polish Apply damage label');
      click('dialog[open] [data-cancel]');check(JSON.stringify(c)===pendingBefore,'cancel damage leaves pending untouched');
      click('#damageHelperButton');input('dialog[open] [name="amount"]','5');click('dialog[open] [data-preview]');
      check(!el('dialog[open] [type="submit"]').disabled,'automatic repeated allocation is applicable');
      click('dialog[open] [type="submit"]');
      check(c.pending.STR===3&&c.pending.DEX===1&&c.current.STR===10&&!c.dead,'apply queues exact preview without changing current dice or killing on overflow');
      check(loadState().characters[0].pending.STR===3,'automatic damage persisted');
    `;
    const html = fs.readFileSync(path.join(__dirname,'index.html'),'utf8')
      .replace('<head>',`<head><base href="${pathToFileURL(__dirname+path.sep)}">`)
      .replace('</body>',`<script>try {${checks};document.body.dataset.testResult='PASS'} catch(error) {document.body.dataset.testResult=error.stack}</script></body>`);
    const file = path.join(dir,'smoke.html'); fs.writeFileSync(file,html);
    const result = spawnSync('chromium',['--headless','--no-sandbox','--disable-gpu','--disable-background-networking',`--window-size=${width},900`,'--allow-file-access-from-files',`--user-data-dir=${path.join(dir,'profile')}`,'--dump-dom',pathToFileURL(file).href],{encoding:'utf8',timeout:20000,maxBuffer:4*1024*1024,env:{...process.env,XDG_CONFIG_HOME:dir}});
    assert.ifError(result.error);
    const outcome = result.stdout.match(/data-test-result="([^"]*)"/);
    assert.equal(outcome?.[1],'PASS',outcome?.[1]||result.stderr);
  } finally {fs.rmSync(dir,{recursive:true,force:true});}
});
